<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ABDTools.Core\ABDTools.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>AppIcon.ico</ApplicationIcon>
    <!-- Optimization: Framework Dependent (requires .NET Runtime installed) -->
    <SelfContained>false</SelfContained>
  </PropertyGroup>

</Project>